# Site settings
title: DEV! UX Design for Engineers
class-title: UX Design for Engineers
blog-title: The UX Blog
favicon: favicon_circle_dev.png
email: uxdsarah@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Learn to create awesome experiences all by yourself. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.uxdesignforengineers.com/" # the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown
